backend:
  name: git-gateway
  branch: master #branch to update (optional, defaults to master)

display_url: https://blog.association-tedua.fr

publish_mode: editorial_workflow

media_folder: "static/img/portfolio" # Media files will be stored in the repo under static/img/portfolio
public_folder: "/img/portfolio" # The src attribute for uploaded media will begin with /img/uploads

collections:
  - name: "accueil" # Used in routes, e.g., /admin/collections/blog
    label: "Articles pour la vie de Château" # Used in the UI
    folder: "content/accueil" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Type_de_bloc", name: "showonlyimage", widget: "boolean"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Position_du_bloc", name: "weight", widget: "number", valueType: "int"}
      - {label: "Date_de_publication", name: "date", widget: "datetime"}
      - {label: "Article", name: "body", widget: "markdown"}
